name: hugo-latest-cd

on:
  push:
    branches:
      - master

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #  HUGO_ARGS: '--minify'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          submodules: true
          fetch-depth: 1
      # - name: Set up Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12.x
      - name: Install tools
        run: |
          npm install
      # - name: Install Hugo
      #   run: |
      #     HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name')
      #     mkdir tmp/ && cd tmp/
      #     curl -sSL https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_extended_${HUGO_VERSION: -6}_Linux-64bit.tar.gz | tar -xvzf-
      #     sudo mv hugo /usr/local/bin/
      #     cd .. && rm -rf tmp/
      #     hugo version
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true
      - name: Clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi
      - name: Build
        run: hugo ${HUGO_ARGS:-""} -d ${DEST:-"docs"}
      - name: Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git